/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kzbdftqsnxieiotwfnsc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6YmRmdHFzbnhpZWlvdHdmbnNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5NTA4NjYsImV4cCI6MjA4MzUyNjg2Nn0.d-kLossLOGP99QJcN5VBPVeifH39_b7ENPOS-sFR_X8"